version: "3.7"
networks:
        default:
                external:
                         # Make network if it doesnt exist
                         # NOTE: Network should be defined in .env file
                         # -> docker network create <NETWORK_NAME>
                         name: "${NETWORK_NAME}"
services:
        web:
                container_name: "flask_sugsn"
                image: flask:sugsn
                build: .
                environment:
                  # Values should be defined in .env file
                        PGID: "${PGID}"
                        PUID: "${PUID}"
                        # The following is for nginx-proxy
                        LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
                        VIRTUAL_HOST: "${VIRTUAL_HOST}"
                        LETSENCRYPT_HOST: "${LETSENCRYPT_HOST}"
                        VIRTUAL_PORT: "${VIRTUAL_PORT}"
                restart: always
                volumes:
                        - ./app:/usr/src/app/
                links:
                        - db
        db:
                container_name: "mongo_sugsn"
                image: mongo:latest
                volumes:
                        - /opt/sugsn/mongo/:/data/db
                restart: always
