version: "3.7"
networks:
        default:
                external:
                         # Make cloudbox network if it doesnt exist
                         # -> docker network create cloudbox
                         name: "cloudbox"
services:
        web:
                container_name: "flask_sugsn"
                image: flask:sugsn
                build: .
                environment:
                        PGID: "1001"
                        PUID: "1000"
                        # The following is for nginx-proxy
                        LETSENCRYPT_EMAIL: "kunaal@ashiana.com"
                        VIRTUAL_HOST: "api.kunaal.dev"
                        LETSENCRYPT_HOST: "api.kunaal.dev"
                        VIRTUAL_PORT: "5000"
                restart: always
                volumes:
                        - .:/usr/src/app/
                links:
                        - db
        db:
                container_name: "mongo_sugsn"
                image: mongo:latest
                volumes:
                        - /opt/sugsn/mongo/:/data/db
                restart: always
